INSERT INTO tasks (title, description, completed) VALUES ('Comprar leche', 'Ir al supermercado y comprar leche', 0);
INSERT INTO tasks (title, description, completed) VALUES ('Hacer ejercicio', '30 minutos de cardio en la mañana', 0);
INSERT INTO tasks (title, description, completed) VALUES ('Leer un libro', 'Leer al menos un capítulo del libro actual', 0);
INSERT INTO tasks (title, description, completed) VALUES ('Llamar al banco', 'Resolver un problema con la cuenta bancaria', 0);
INSERT INTO tasks (title, description, completed) VALUES ('Organizar el escritorio', 'Limpiar y organizar el escritorio de trabajo', 0);
INSERT INTO tasks (title, description, completed) VALUES ('Preparar presentación', 'Trabajar en la presentación para la reunión de mañana', 0);
INSERT INTO tasks (title, description, completed) VALUES ('Responder correos', 'Revisar y responder correos electrónicos importantes', 0);
INSERT INTO tasks (title, description, completed) VALUES ('Pagar facturas', 'Pagar las facturas del mes', 0);
INSERT INTO tasks (title, description, completed) VALUES ('Revisar código', 'Realizar una revisión del código fuente del proyecto', 0);
INSERT INTO tasks (title, description, completed) VALUES ('Correr 5 km', 'Salir a correr 5 kilómetros en la tarde', 0);